import { Badge } from "@/components/ui/badge";
import interiorImage from "@assets/stock_images/yumyum.jpg";
import { Flame, Star, Clock } from "lucide-react";

export default function About() {
  return (
      <section id="about" className="py-24 bg-black relative overflow-hidden">
            {/* Decorative accent */}
                  <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 blur-[100px] rounded-full pointer-events-none" />

                        <div className="container mx-auto px-4">
                                <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                                          {/* Text Content */}
                                                    <div className="space-y-8 order-2 lg:order-1">
                                                                <div className="space-y-4">
                                                                              <Badge variant="outline" className="text-primary border-primary/20 px-4 py-1 uppercase tracking-widest text-xs">
                                                                                              Nuestra Historia
                                                                                                            </Badge>
                                                                                                                          <h2 className="text-4xl md:text-5xl font-heading font-bold text-white uppercase">
                                                                                                                                          Pasión por el <span className="text-primary">Sabor Urbano</span>
                                                                                                                                                        </h2>
                                                                                                                                                                    </div>
                                                                                                                                                                                
                                                                                                                                                                                            <p className="text-gray-400 leading-relaxed text-lg">
                                                                                                                                                                                                          Yum-Yum nació en el corazón de la ciudad con una misión simple pero ambiciosa: crear las alitas y boneless más adictivos que hayas probado. No somos solo un restaurante de comida rápida, somos un destino culinario para los amantes del sabor intenso.
                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                              <p className="text-gray-400 leading-relaxed text-lg">
                                                                                                                                                                                                                                                            Nuestra filosofía se basa en tres pilares: salsas artesanales preparadas diariamente, pollo fresco de la más alta calidad y un ambiente que te invita a quedarte y disfrutar con amigos.
                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-3 gap-6 pt-6">
                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                  <Flame className="text-primary mb-2" size={32} />
                                                                                                                                                                                                                                                                                                                                  <h4 className="text-2xl font-bold text-white">5+</h4>
                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-500 uppercase tracking-wider">Años de Sabor</p>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                              <Star className="text-primary mb-2" size={32} />
                                                                                                                                                                                                                                                                                                                                                                                                              <h4 className="text-2xl font-bold text-white">15k+</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-gray-500 uppercase tracking-wider">Clientes Felices</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Clock className="text-primary mb-2" size={32} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h4 className="text-2xl font-bold text-white">3</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-gray-500 uppercase tracking-wider">Sucursales</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Image Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative order-1 lg:order-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="relative z-10 rounded-lg overflow-hidden border border-white/10 shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="absolute inset-0 bg-primary/10 mix-blend-overlay z-20 pointer-events-none" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          src={interiorImage} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt="Interior del restaurante Yum-Yum" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full h-auto object-cover transform hover:scale-105 transition-transform duration-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Offset border effect */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="absolute -bottom-4 -right-4 w-full h-full border-2 border-primary/30 rounded-lg z-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
